title: ClickerCentral
description: Formative assessment questions for teaching physics
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
github:
  repository_name: ClickerCentral
  owner_name: Ian Beatty