# This file stores various settings for your site.
# You can include the values of these fields in markdown, e.g.:
# {{ site.data.settings.name }}

# The main name of your site
name: "ClickerCentral"

# A tagline for your site, often shown with the name
tagline: "Formative assessment questions for teaching physics"

# A description of your site, e.g. for social-media snippets
description: "An archive of Assessing-to-Learn (A2L) formative assessment questions from the UMass Physics Education Research Group (UMPERG)"

# The main language of your site. Use the IANA language subtag.
# See https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
# or lookup here: https://r12a.github.io/app-subtags/
language: "en"

# A default image for your site, e.g. for social-media snippets
image: "avatar.png"

# The logo for your site, if you have one
logo: "logo.png"

# The final, canonical address of your live site
url: "http://ibeatty.github.io/clickercentral"

# Your Google Analytics ID, if you're using Google Analytics
# google-analytics-id: "UA-00000000-0"

# Your email address, e.g. for the contact form to use
email: "idbeatty@uncg.edu"
